### PR TITLE
Use .row instead .item for UITableView IndexPaths

### PR DESCRIPTION
**Pull request by Tawfikk**
Why do you use .item for tableView insted .row ?

### CODE REVIEW

**Comment by richardxyx** [comment]
I use .item instead of .row because the two are [functionally identical](https://stackoverflow.com/a/17182239/4893137). I see why you would use .row with UITableViews though.

**Comment by Tawfikk** [comment]
screenshot 2017-07-22 02 20 58

**Comment by richardxyx** [comment]
Please change the commit message to "Use .row instead .item for UITableView IndexPaths" and undo the changes to Main.storyboard, I agree that you would use .row with UITableViews and will merge it then.

**Comment by Tawfikk** [comment]
it's okay ?

**Pull request merged**
